### ISSUE TITLE
Texlive version requirements

### ISSUE THREAD

**Issue by dekura** [Trinkle23897/THU-Beamer-Theme#1]
Hi, 
Thanks for the awesome template.
The `texlive 2020` can not compile this template because the `pgf` package.
I successful compile it using the `texlive 2018`.
I am wondering whether it can be update to the `texlive 2020` version~

Thank you.

**Comment by Trinkle23897** [comment]
But I tested with `texlive 2020` + `\usepackage{pgf}`, no error occurs.
[log.txt](https://github.com/Trinkle23897/THU-Beamer-Theme/files/4791335/log.txt)
Could you please provide your log and compilation environment?

**Comment by dekura** [comment]
> But I tested with `texlive 2020` + `\usepackage{pgf}`, no error occurs.
> [log.txt](https://github.com/Trinkle23897/THU-Beamer-Theme/files/4791335/log.txt)
> Could you please provide your log and compilation environment?

Thank you for the quick reply,
I updated the `pgf` package and it works.
