### ISSUE TITLE
请问如何在这个模板中显示右下角按钮呢

### ISSUE THREAD

**Issue by KairuiLiu** [Trinkle23897/THU-Beamer-Theme#2]
rt

**Comment by Trinkle23897** [comment]
能举个具体的例子吗，比如你想要的右下角按钮长啥样，功能是啥？

**Comment by KairuiLiu** [comment]
您好，就是如图所示的默认按钮
![image](https://user-images.githubusercontent.com/25458969/100206261-11074180-2f41-11eb-89de-c37b4a6965ab.png)

谢谢

**Comment by Trinkle23897** [comment]
把 https://github.com/Trinkle23897/THU-Beamer-Theme/blob/c98d36ef2a3858cecb165ff63b51c2b7504b6d48/Tsinghua.sty#L44 注释掉就行

**Comment by KairuiLiu** [comment]
多谢
