### ISSUE TITLE
每一页最上面一行的目录下对应的小点

### ISSUE THREAD

**Issue by Technew94** [Trinkle23897/THU-Beamer-Theme#9]
请问每一页最上面一行的目录下对应的小点是哪个包的功能呢？这个功能叫做什么呢？

**Comment by Trinkle23897** [comment]
https://github.com/tuna/THU-Beamer-Theme/blob/061f088d1c7e4b2d2f1f581f3745945ecbb63f25/Tsinghua.sty#L9
可以注释掉这一行编译一下看看

**Comment by Technew94** [comment]
Thank you for your reply, the command below is very helpful to my questions!

\useoutertheme[subsection=false]{miniframes}
